//! PHP FastCGI of a site. The shared Caddy in `router` serves it over HTTPS.

use crate::model::Ports;
use crate::paths::project_dir;
use crate::ports;
use crate::process::{hidden_command, spawn_logged, ManagedChild};
use crate::runtimes;
use anyhow::Result;
use std::fs;
use std::path::Path;

/// Starts php-cgi from the site's PHP line and assigns the site's ports.
pub(crate) fn start_php(
    root: &Path,
    project_id: &str,
    project_path: &Path,
    php_line: &str,
    ports: &mut Ports,
    children: &mut Vec<ManagedChild>,
) -> Result<()> {
    let php_dir = runtimes::line_dir(
        root,
        "php",
        &runtimes::resolve_line(root, "php", Some(php_line), "PHP")?,
    );
    // Fail before starting anything when Caddy is missing.
    runtimes::resolve_line(root, "caddy", None, "Caddy")?;
    crate::router::public_dir(project_path)?;
    ports::assign(ports, "site")?;
    let fastcgi_port = ports::assign(ports, "fastcgi")?;
    let directory = project_dir(root, project_id);
    fs::create_dir_all(&directory)?;

    let mut php_command = if cfg!(windows) {
        let mut command = hidden_command(php_dir.join(runtimes::exe("php-cgi")));
        command
            .arg("-c")
            .arg(php_dir.join("php.ini"))
            .arg("-b")
            .arg(format!("127.0.0.1:{fastcgi_port}"));
        command
    } else {
        // macOS and Linux builds ship php-fpm instead of php-cgi.
        let config = directory.join("php-fpm.conf");
        fs::write(&config, fpm_config(fastcgi_port, project_path))?;
        let mut command = hidden_command(php_dir.join("php-fpm"));
        command
            .arg("--nodaemonize")
            .arg("--fpm-config")
            .arg(&config)
            .arg("-c")
            .arg(php_dir.join("php.ini"));
        command
    };
    php_command.current_dir(project_path);
    let mut php_process = spawn_logged(&directory, "php", php_command)?;
    let ready = ports::wait_until_listening(fastcgi_port, &mut php_process.child, "PHP FastCGI");
    children.push(php_process);
    ready
}

/// One php-fpm pool for the site, in the foreground, logging to stderr (the site's php log).
fn fpm_config(port: u16, project_path: &Path) -> String {
    format!(
        "; Generated by Werd for this site; rewritten on every start.\n\
         [global]\n\
         error_log = /dev/stderr\n\
         log_level = notice\n\
         daemonize = no\n\
         \n\
         [site]\n\
         listen = 127.0.0.1:{port}\n\
         chdir = \"{path}\"\n\
         ; Keep the environment, like php-cgi on Windows (PATH, WERD_*, …).\n\
         clear_env = no\n\
         catch_workers_output = yes\n\
         decorate_workers_output = no\n\
         pm = ondemand\n\
         pm.max_children = 10\n\
         pm.process_idle_timeout = 30s\n",
        path = project_path.display()
    )
}
